### ISSUE TITLE
The plugin does not show bookmarks

### ISSUE THREAD

**Issue by universish** [Insiderser/AutoFullscreen#9]
When I activate the plugin in firefox (latest version) the bookmarks do not appear. The options “show bookmarks” or “hide bookmarks” do not work. when I drag the mouse to the bar the bookmarks do not appear in the floating drawer. 
Even when the add-on is disabled/inactive and the F11 key works, the drawer opens when the mouse is dragged to the bar and the bookmarks are still not visible.

 - OS: [Nobara Linux 40 (GNOME Edition) (Fedora 40) ]
 - Kernel: [Linux 6.10.3-201.fsync.fc40.x86_64]
 - Firefox version [128.0.3]
 - App version [2.04]

**Comment by insiderser** [comment]
Hey @hureyre. Thanks for reporting this issue!

You can enable showing the bookmarks bar in fullscreen mode by following the steps described in https://support.mozilla.org/en-US/questions/1374693. I use it personally. Kindly let me know if the link resolves your issue.

**Please note (legal disclaimer): The link above is shared on informational basis, and I am not responsible for any damage or data loss that might occur while doing those steps, in particular by doing something wrong.**

I intentionally want to keep this add-on simple. I want it to do only one thing. All this add-on does is just "pressing" the F11 key when a new Firefox window is opened. Everything after that is the default in-fullscreen-mode Firefox experience. Modifying that experience is something outside the scope of this add-on.
